# Generated by Django 5.1.5 on 2025-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_transaction_is_income_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('health', 'Health'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
